module("profileCommon", package.seeall)

local path = "script.game.mvc.model.profile_common.Profile_"

BindPhone = Load.LuaRequire(path .. "BindPhone")
BindWechat = Load.LuaRequire(path .. "BindWechat")
BuyGoods = Load.LuaRequire(path .. "BuyGoods")
CashAward = Load.LuaRequire(path .. "CashAward")
CashPrize = Load.LuaRequire(path .. "CashPrize")
ConvertList = Load.LuaRequire(path .. "Convert")
HuoDong = Load.LuaRequire(path .. "HuoDong")
IAPPayResult = Load.LuaRequire(path .. "IAPPayResult")
IDLE = Load.LuaRequire(path .. "IDLE")
InitImageList = Load.LuaRequire(path .. "InitImageList")
LoadWebView = Load.LuaRequire(path .. "LoadWebView")
Script = Load.LuaRequire(path .. "LuaScriptUpdata")
Marquee = Load.LuaRequire(path .. "Marquee")
Message = Load.LuaRequire(path .. "Message")
ModifyUserInfo = Load.LuaRequire(path .. "ModifyUserInfo")
MoreUser = Load.LuaRequire(path .. "MoreUser")
MyPrize = Load.LuaRequire(path .. "MyPrize")
NetErr = Load.LuaRequire(path .. "NetErr")
PriceCompound = Load.LuaRequire(path .. "PriceCompound")
Prize = Load.LuaRequire(path .. "Prize")
ResetPass = Load.LuaRequire(path .. "ResetPass")
SendSMS = Load.LuaRequire(path .. "SendSMS")
ServerConfig = Load.LuaRequire(path .. "ServerConfig")
ServerMsg = Load.LuaRequire(path .. "ServerMsg")
SuipianPrize = Load.LuaRequire(path .. "SuipianPrice")
UserLoginReg = Load.LuaRequire(path .. "UserLoginReg")
Version = Load.LuaRequire(path .. "Version")
ImageToast = Load.LuaRequire(path .. "ImageToast")
RedPackets = Load.LuaRequire(path .. "RedPackets")
